- name: Ensure {{ metallb_namespace }} namespace exists
  k8s:
    name: "{{ metallb_namespace }}"
    api_version: v1
    kind: Namespace
    state: "{{ metallb_state }}"
    validate_certs: "{{ metallb_validate_k8s_certs }}"
  delegate_to: 127.0.0.1
  run_once: true

- name: Ensure MetalLB ConfigMap exists
  k8s:
    definition: "{{ lookup('template', 'configmap.yaml.j2') }}"
    namespace: "{{ metallb_namespace }}"
    state: "{{ metallb_state }}"
    validate_certs: "{{ metallb_validate_k8s_certs }}"
  delegate_to: 127.0.0.1
  run_once: true
  # tags: [postgres, configmap, postgres_configmap]

- name: Ensure MetalLB Secret exists
  k8s:
    definition: "{{ lookup('template', 'secret.yaml.j2') }}"
    namespace: "{{ metallb_namespace }}"
    state: "{{ metallb_state }}"
    validate_certs: "{{ metallb_validate_k8s_certs }}"
  delegate_to: 127.0.0.1
  run_once: true

- name: Ensure MetalLB deployment exists
  k8s:
    definition: "{{ lookup('template', 'metallb.yaml.j2') }}"
    namespace: "{{ metallb_namespace }}"
    state: "{{ metallb_state }}"
    validate_certs: "{{ metallb_validate_k8s_certs }}"
  delegate_to: 127.0.0.1
  run_once: true