apiVersion: v1
kind: Namespace
metadata:
  name: metallb-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metallb
  namespace: argocd
spec:
  destination:
    namespace: metallb-system
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      selfHeal: yes
  source:
    repoURL: https://metallb.github.io/metallb
    chart: metallb
    targetRevision: 0.12.1
    helm:
      values: |
        configInline:
          address-pools:
          - name: default
            protocol: layer2
            addresses: []
            
# - 65.108.63.168/32
# - 65.108.86.186/32